name: Run tests and example installer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Run tests
      run: cargo test --verbose

  example:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    name: Test example installer on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Run example install
      run: cargo run --example takecrate_example_installer -- self install --quiet
    - name: Run example uninstall
      run: cargo run --example takecrate_example_installer -- self uninstall --quiet